# ============================================= #
#            ChatImage Configuration            #
#              By: ChickenSaysBak               #
#                                               #
# To reload, use /chatimage reload              #
#                                               #
# Permissions:                                  #
# - chatimage.use (to render images)            #
# - chatimage.admin (to use /chatimage)         #
# ============================================= #


# IMAGE SETTINGS #

# Uses a more visually pleasing method of rendering images.
# This is nearly just as fast as alternative rendering.
smooth_render: true

# Gets rid of excessive blank space along edges.
trim_transparency: true

# Maximum dimensions for an image. The maximum for default Minecraft chat settings is 35 x 20.
# See HIDDEN IMAGE SETTINGS for changing the dimensions of hidden images.
max_width: 35
max_height: 20


# COOLDOWN SETTINGS #

# Sets how long (in seconds) someone must wait before another image will render.
cooldown: 3

# Cooldown will start from 0 if an image URL is sent (as opposed to it starting when the image itself renders).
# If enabled, this lengthens the cooldown if the user is repeatedly sending a URL. This can help against avid spammers.
strict_cooldown: false


# HIDDEN IMAGE SETTINGS #

# When a player runs /hideimages, images sent in chat are minimized, and they can be viewed by hovering.
# Hidden images that are wide will appear smaller than normal.
hidden_images:

  # Hides images by default. Players can individually override this with /showimages.
  # If enabled, consider reducing the cooldown since this option already reduces line spam.
  auto_hide: false

  # Maximum dimensions for hidden images only.
  # If you increase the width, beware that you risk creating broken images for users on a smaller window size or bigger GUI scale.
  # Conversely, on a smaller GUI scale, you can render way larger images, but there's no way to know who's using what scale.
  # 23 x 24 is a safe default for the standard 854 x 480 window or larger.
  # If you don't mind potentially breaking images for some users, you can increase it to 26 x 27 for full-screen users.
  max_width: 23
  max_height: 24


# FILTRATION SETTINGS #

explicit_content:

  # Prevents an image from rendering if explicit content is found. Does not apply to '/chatimage send'
  # This will impact speed by a couple seconds. Duplicate images cache within the plugin to increase speed.
  # Feature provided by: https://api4.ai/apis/nsfw
  enabled: false

  # If an image contains explicit content, the entire message with the link will not be sent.
  # NOTE: This includes messages from people that do not have permission to render images.
  remove_message: false


# GENERAL SETTINGS #

# The default language to use if a player's client language is unsupported.
# You can add languages in the messages folder. Please consider sharing these on the plugin's GitHub or SpigotMC page!
# If adding a language, name the file with a valid in-game language code: https://minecraft.wiki/w/Language#Languages
language_default: en_us

# Prints extra messages to console to help find the source of issues
debug: false
