name: ChatImage
author: ChickenSaysBak
website: https://www.spigotmc.org/resources/chatimage-send-images-in-minecraft.95842/
description: Send images in Minecraft!
version: ${project.version}
api-version: 1.16
softdepend: [DiscordSRV]
main: me.chickensaysbak.chatimage.core.plugin.spigot.PluginSpigot
commands:
  chatimage:
    description: Admin command for the ChatImage plugin.
    permission: chatimage.admin
  ignoreimages:
    description: Hides images created by links in chat.
